apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-pod

spec:
  replicas: 3
  selector:
    app: my-app
    
  template:
    metadata:
      name: nginx-pod
      labels:
        app: my-app

    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80